# Generated by Django 6.0.5 on 2026-06-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_portfolio_services_testimonial_titles_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
    ]
