# Generated by Django 6.0.5 on 2026-06-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_rename_services_service_rename_titles_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video1', models.URLField(default='https://www.youtube.com/embed/dQw4w9WgXcQ')),
                ('video2', models.URLField(default='https://www.youtube.com/embed/ypy4m_L680A')),
                ('video3', models.URLField(default='https://www.youtube.com/embed/EngW7tLk6r8')),
                ('showHeroTexts', models.BooleanField(default=True)),
                ('phase1Label', models.CharField(default='PHASE 01 // INTERVIEW ARCHITECTURE', max_length=200)),
                ('phase1Title', models.CharField(default='We Extract Your Core Narrative', max_length=200)),
                ('phase1Desc', models.TextField(default='Our production team conducts targeted, high-fidelity conversational mappings to gather raw authority assets.')),
                ('phase2Label', models.CharField(default='PHASE 02 // RETENTION ASSEMBLY', max_length=200)),
                ('phase2Title', models.CharField(default='Applying High-Performance Cuts', max_length=200)),
                ('phase2Desc', models.TextField(default='Refining auditory beats, adding volt structural graphics, and formatting hooks to capture organic feeds.')),
                ('phase3Label', models.CharField(default='PHASE 03 // FULL-SCALE EXPANSION', max_length=200)),
                ('phase3Title', models.CharField(default='The Absolute Distribution Cadence', max_length=200)),
                ('phase3Desc', models.TextField(default='Your brand claims real estate on TikTok, Reels, Shorts, and LinkedIn simultaneously. Scroll down to deploy your engine.')),
                ('heroSubtitle', models.TextField(blank=True, default='')),
                ('testimonialSubtitle', models.CharField(default='PARTNER REVIEWS', max_length=200)),
                ('testimonialTitle', models.CharField(default='PROVEN SYSTEM REPUTATION', max_length=200)),
                ('testimonialDescription', models.TextField(default='Discover observations from leaders who scale their presence using our systematic workflows.')),
            ],
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='company',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='review',
            new_name='quote',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='metric',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='title',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
