# Generated by Django 6.0.5 on 2026-06-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_websitesettings_rename_company_testimonial_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='bookingSubtitle',
            field=models.TextField(default='Book a diagnostic call to map your distribution framework inline instantly.'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='bookingTitle',
            field=models.CharField(default='ALIGN THE FLUID PROCESS', max_length=200),
        ),
    ]
