# Generated by Django 6.0.5 on 2026-06-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_websitesettings_bookingsubtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='video1',
            field=models.CharField(default='https://www.youtube.com/embed/dQw4w9WgXcQ', max_length=500),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='video2',
            field=models.CharField(default='https://www.youtube.com/embed/ypy4m_L680A', max_length=500),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='video3',
            field=models.CharField(default='https://www.youtube.com/embed/EngW7tLk6r8', max_length=500),
        ),
    ]
