# Generated by Django 6.0.5 on 2026-06-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_alter_websitesettings_video1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='heading',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='title',
            name='sub_heading',
            field=models.CharField(max_length=200),
        ),
    ]
